### ISSUE TITLE
File->Export all dialog doesn't allow Enter within browsing.

### ISSUE THREAD

**Issue by franc6** [franc6/Ketarin#14]
When I tried my first
File->Export all
to export all recipes from the database to an XML file, I typed in part of the path to where I wanted to save the file, "/data/LT", then tapped Enter to change to that folder to see where I wanted to go next, but the dialog closed.
I later found a file in /data/LT called ".XML", so it seems the program decided I had finished browsing and wanted to save now, even though the filename part was empty, and saved just the dot-extension part.
We should be able to explore part of the way to somewhere, then tap Enter to open that folder, then type some initial letters to select the next folder in the path, or click in the folders on display to select one, or even Shift-Tab to step in amongst the folders on display.
The attached screenshot shows the point at which I first tapped Enter to open the intermediate folder, and the dialog closed.

See 
https://drive.google.com/file/d/1xJlO8X_CB_qMKXI10bMsHLqoVLcxObM0/view?usp=sharin
g

Reported by Jim Henderson

**Comment by franc6** [comment]
I think I see what's going on. You're not comparing apples to apples. :)
With Notepad, you're not just typing in a folder name, you're choosing from a droplist (implicitly, but look at the droplist). You do this explicitly with Ketarin on Windows, too. And there's a difference. If the folder name isn't in the drop list (with the exception of anything that ends with ), it won't browse, it'll create a file with the name + default extension. The reason it won't do that for stuff ending with \ is simple -- Windows likes to pretend file names can't start with "." and so the dialog can assume you want to browse, not choose a file.
I won't claim to know exactly what's happening with gedit, since I'm not a GTK developer. But I do know what's going on with Windows, and it's not quite what you think. I realize it's confusing, and probably looks inconsistent, but it's not.
Anyway, that's all behavior that's outside of our control.
The part that may be in our control is handling a blank file name -- that should be rejected. Again, on Windows, I'd know exactly what to do. I need to do some testing on Linux, to see if I can control that behavior. If so, then I should be able to make it browse as long as you end whatever you type with a /.

**Comment by franc6** [comment]
We're not going to be able to do much about this.  Mono's implementation doesn't expose any method of programmatically changing the directory of the dialog.  I can add code to reject a file name such as ".xml", but I cannot cause the directory to be changed within the dialog.

For future reference, the problem is that we would need to call either FileDialog.mwfFileView.ChangeDirectory(), or FileDialog.SetFileAndDirectory().  Both mwfFileView and SetFileAndDirectory() are marked as private, so we cannot access them.  Any attempt to do so would require re-implementing FileDialog (and a pair of private classes it uses) and SaveFileDialog.  Either would be annoying to maintain going forward.

Possible fixes:

1) Silently reject saving a file name ".xml" in any directory.  The user wouldn't notice much, except that typing "/home" and pressing enter (or clicking the Save button) would appear to do nothing at all.

2) When the dialog attempts to suggest a file name of ".xml", ask the user if they really want to save a hidden file named "<path>/.xml".  If the user clicks Yes, accept the name, and attempt to save it.  If the user says no, reject the name, and the user is left with the Save dialog on screen with no apparent changes -- the dialog didn't browse to the given directory, and the dialog still shows whatever the user has typed.

Let me know which you'd prefer.

**Comment by JimH44** [comment]
Your comment where you suggest the Save As dialog would continue browsing if I end the suggested name with / doesn't work.
I like your option 2 better. We also need to reject saving "...xml", in case the user wants to go back a level towards the root of the filesystem and types ".." and taps Enter.
I'll think some more about this.

**Comment by franc6** [comment]
I think you misunderstood my comment about ending a name with /.  I had suggested that I _might_ be able to make that work.  I can't -- Mono doesn't expose the necessary API -- it's marked as "private" instead of "public".  Even just "protected" would let me fix it. :(

Ignore commit d8dabf7, please.  It's not the fix you were requesting; I accidentally pushed all, forgetting that commit was there.  I should have the correct fix soon, but it won't be available in the Mono branch until after I've worked out the appropriate fix for #32 with floele.

**Comment by franc6** [comment]
Fix is now in the Mono branch.

**Comment by JimH44** [comment]
Very nice!
I can now browse within the filename field as in the Windows version. I find that much quicker than clicking on folders.
Thanks Tom :-)
