### ISSUE TITLE
Crash when sorting

### ISSUE THREAD

**Issue by franc6** [franc6/Ketarin#15]
This seems to happen all the time after initially clicking a column header to sort.

This appears to be a bug in mono? I see an IndexOutOfRangeException from a method called at line 1559. If I simply catch and ignore that exception, I get the same exception at line 1555 on the next iteration of the loop. The stack trace is similar in each case, and appears to be related to actually adding items to the ListView.

Needs more research...

**Comment by franc6** [comment]
There have been a lot of changes from the original author of ObjectListView since the version in Ketarin (1.13, latest is 2.9.1 as of Sep 28 2020).  Some of those changes address sorting and groups.  The error is caused when updating the view after sorting.  It still looks like a bug in Mono to me.  If I change the code to add each item one at a time, instead of several at a time, it works.  This makes the application a little slower, but I figure slow is better than crashing.

**Comment by JimH44** [comment]
Sorting columns works nicely without any crashes, and doesn't seem slow to me. :-)
