### ISSUE TITLE
Case mismatch in filename ProgressDialog.Designer.cs

### ISSUE THREAD

**Issue by JimH44** [franc6/Ketarin#29]
Build error
/data/Ketarin4Linux/CSC: Error CS2001: Source file '/data/Ketarin4Linux/CDBurnerXP/ProgressDialog.**designer.cs**' could not be found. (CS2001) (Ketarin)
Ketarin.csproj has _designer_ in lower case, but the filename has it with a capital D.
I modified my csproj and the build succeeded.

**Comment by JimH44** [comment]
It's fixed in the Mono version. I must have fetched the wrong version before.

**Comment by franc6** [comment]
This is issue #1
