### ISSUE TITLE
New KFileDialog should save column widths

### ISSUE THREAD

**Issue by franc6** [franc6/Ketarin#44]
Column widths in the details view should be saved and restored.

**Comment by franc6** [comment]
Fixed in commit bced0397ece4fe98825041f8c7968159b8de6952.
 
Added code to save and restore the column widths from the details view.  This is also stored in the registry under HKEY_CURRENT_USER.  See ${HOME}/.mono/registry/CurrentUser/software/kfiledialog/values.xml

**Comment by JimH44** [comment]
Yes, column widths are remembered.
