### ISSUE TITLE
icon stuck in Waiting after editing

### ISSUE THREAD

**Issue by JimH44** [franc6/Ketarin#48]

**Comment by JimH44** [comment]
When I edit a "recipe" and close the edit dialog, the cursor remains stuck in the "Waiting" form, like a wheel. It doesn't rotate, just stays static.
As I move the cursor down, there is an area near the bottom of the window where the normal cursor appears. See the screenshot.
![icon stuck in Waiting](https://user-images.githubusercontent.com/8330030/70679214-940b9980-1ce8-11ea-8975-369c5a286bcb.jpg)

**Comment by franc6** [comment]
This is where not being a regular user causes problems. :(  I can see the few places in the code where the cursor is changed, but I haven't been able to trigger them.  :(  It also looks like it's changed correctly, so the cursor should go back to normal.

Can you include info on which recipe you were editing, what changes you made to it (if any) and how you closed the dialog (enter, esc, clicked cancel, or clicked OK)?  That'll help me reproduce it, and fix it.  Even if it's a Mono bug, I might be able to work around it, if I can reproduce it.  Without reproducing it, I could just add code that tries to force it back to normal, but that's pretty heavy-handed and could cause both too much memory usage as well as odd flickering.

**Comment by JimH44** [comment]
I think this is fixed now. I'll close the issue, and may reopen it if the problem happens again.
