### ISSUE TITLE
Index outside bounds of array when clicking a column to sort

### ISSUE THREAD

**Issue by JimH44** [franc6/Ketarin#50]
Ketarin-Mono-1.0.36 had been working nicely on Lubuntu 16.04. I had been away doing other things, and came back to find it crashed with this error.
The full crash log is attached.
[crash-2020-02-18.txt](https://github.com/franc6/Ketarin/files/4215936/crash-2020-02-18.txt)

**Comment by franc6** [comment]
Duplicate of #15.  The log clearly indicates a column was clicked to sort; this is probably an artifact of where you clicked when you "came back" to Ketarin.
